Refactor with a more "unit-test" like approach, + enforce some tests as error (instead of warning) for moaaar quality
YunoHost/package_linter pull request #85
Opened 2020-10-08 15:16 UTC by alexAubin

Sooooo started working on this mostly because I wanted to be able to do bulk analysis of the linter results on all apps (or all level 5+ apps) to then be able to flag some stuff as errors (instead of warnings) and be able to check what apps are impacted.

For this, I needed a json output with some error-code-like flags, and ended up refactoring the entire script to have more of a atomic/unit-test-like approach (though could still be improved...) instead of huge functions calling `print()`

After this, I ran a study over all the level 5+ apps to check what could / should now be reported as error ... and also what's the status of some tests like path traversal issue over all apps ...

So far this refactoring introduces the following "regressions" on currently level 5+ apps (meaning releasing this new version of the linter would decrease the level to 4) : 
- (because of path traversal issue) : 
    - garradin
    - zap
    - hubzilla
    - snipeit
    - z-push
    - transmission
    - friendica
    - discourse
    - mailman

- (because of version format)
    - blogotext
    - zabbix
    - friendica
    - strut

I'm also wondering about adding a test that would flag the linter as failing if there's more than X warnings ... So far, among the 150ish apps level 5+, about 90 of them have 0, 1, or 2 warnings (congratz all the packaging folks !). If we look at the "apps with 10+ warnings" we have something like : 

```
10 lionwiki-t2t
10 multi_webapp
10 my-mind
11 borg
11 qr
13 cowyo
13 garradin
13 limesurvey
13 snipeit
13 zap
15 zabbix
17 friendica
17 radicale
18 hubzilla
22 keeweb
```

and I'm **tempted to set the treshold at something like 15 (so 15 or more warnings = error)

Possibly I'm also wondering about report as error apps that still only request Yunohost >= 2.x (instead of 3.x or 4.x) because that may mean they are not up to date with relatively recent packaging practices (a lot happened since 2.7...) - or maybe these are just apps who do not care so much about maintaining the yunohost version requirement ...

For this we would have : 
- borg
- gogs
- libreto
- redirect
- zap

2020-10-11 00:17 UTC, zamentur commented
> (because of version format)
> 
>     * blogotext
> 
>     * zabbix
> 
>     * friendica
> 
>     * strut
Fixed on these 4 repos

2020-10-25 11:09 UTC, alexAubin commented
Created a bunch of PR to hopefully fix the path traversal issues ..
- https://github.com/YunoHost-Apps/garradin_ynh/pull/28
- https://github.com/YunoHost-Apps/zap_ynh/pull/5
- https://github.com/YunoHost-Apps/hubzilla_ynh/pull/43
- https://github.com/YunoHost-Apps/z-push_ynh/pull/61
- https://github.com/YunoHost-Apps/anfora_ynh/pull/17
- https://github.com/YunoHost-Apps/transmission_ynh/pull/75
- https://github.com/YunoHost-Apps/friendica_ynh/pull/36
- https://github.com/YunoHost-Apps/discourse_ynh/pull/63
- yolocommit on Mailman: https://github.com/YunoHost-Apps/mailman_ynh/commit/abade914eadae1891df31ac5e74474b7473b3056

2020-11-08 07:10 UTC, ericgaspar requested changes
Small typos

2020-11-08 07:10 UTC, ericgaspar commented on package_linter.py
> +            yield Warning("'non-free' apps cannot be integrated in Yunohost's app catalog.")
```suggestion
            yield Warning("'non-free' apps cannot be integrated in YunoHost's app catalog.")
```

2020-11-08 07:10 UTC, ericgaspar commented on package_linter.py
>              yield Warning("This app is not Yunohost's application catalog")
```suggestion
            yield Warning("This app is not YunoHost's application catalog")
```

2020-11-08 07:10 UTC, ericgaspar commented on package_linter.py
> +            yield Error("You should make sure that the revision used in Yunohost's apps catalog is HEAD ...")
```suggestion
            yield Error("You should make sure that the revision used in YunoHost's apps catalog is HEAD...")
```

2020-11-08 07:10 UTC, ericgaspar commented on package_linter.py
> +            yield Warning("The application is not flagged as working in Yunohost's apps catalog")
```suggestion
            yield Warning("The application is not flagged as working in YunoHost's apps catalog")
```

2020-11-08 07:10 UTC, ericgaspar commented on package_linter.py
> +            yield Warning("The application is flagged as not maintained in Yunohost's apps catalog")
```suggestion
            yield Warning("The application is flagged as not maintained in YunoHost's apps catalog")
```

2020-11-08 07:10 UTC, ericgaspar commented on package_linter.py
> +            yield Warning("The application has no associated category in Yunohost's apps catalog")
```suggestion
            yield Warning("The application has no associated category in YunoHost's apps catalog")
```

2020-11-09 02:38 UTC, alexAubin commented
Alrighty folks let's merge this in and move forward ... Note that it's expected some of the previously mentioned apps will fail linter because even though the issue got patched it's still only patched in 'testing' but hopefully that'll encourage people to merge the fixes in master...

2020-11-09 02:38 UTC, merged